const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.TileMovement,
		C3.Behaviors.scrollto,
		C3.Behaviors.LOS,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.TileMovement.Cnds.IsMovingDirection,
		C3.Plugins.Sprite.Acts.SetMirrored
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Solid: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Keyboard: 0},
	{DialogueText: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite4: 0},
	{TileMovement: 0},
	{ScrollTo: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{DialogueText2: 0},
	{Sprite9: 0},
	{Caption1: 0},
	{Sprite10: 0},
	{FjF1gPEdec1hB5T8QARJI6rdczURoZX9sWqkuHGs9beGf47il5ZySPj5soqLM2VlYnRBuD_Irs0PpPPMD4xtjxRPAbFM9cjgZoGyUeCcvHYUrOsNJBRUPXrM6kXl8xTdRW0YkC_PjIHfssKoBbZiaVAxqysgAAtfu0Vtm9zpuMzXx7MhLsqLIAXGrUJdSQuxSsGOhFxr_ePjDV2JaiOzV4rWrjNYqf1TbsDNUNMj3EMDzU03bWhzM41gq48VEZ9gGGqfZl24E2rmr5mjO02l1ISJy5oCthWXqCEWwWyQDeTG5hZAFAme64q_3FYq1xlteMFsB9wpBFoRMPA3Q: 0},
	{Caption3: 0},
	{Caption2: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Caption4: 0},
	{Sprite13: 0},
	{DialogueText3: 0},
	{imrs: 0},
	{Caption5: 0},
	{LineOfSight: 0},
	{Sprite14: 0},
	{Sprite15: 0},
	{DialogueText4: 0},
	{e3e2e3fa5af344168d7e54d687bf276d: 0},
	{Caption6: 0},
	{Sprite16: 0},
	{TextOnSign: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{DialogueXTRA: 0},
	{children: 0},
	{prisoners: 0},
	{Caption7: 0},
	{Caption8: 0},
	{Sprite19: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	DialogueText: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	DialogueText2: class extends self.ITextInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Caption1: class extends self.ITextInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	FjF1gPEdec1hB5T8QARJI6rdczURoZX9sWqkuHGs9beGf47il5ZySPj5soqLM2VlYnRBuD_Irs0PpPPMD4xtjxRPAbFM9cjgZoGyUeCcvHYUrOsNJBRUPXrM6kXl8xTdRW0YkC_PjIHfssKoBbZiaVAxqysgAAtfu0Vtm9zpuMzXx7MhLsqLIAXGrUJdSQuxSsGOhFxr_ePjDV2JaiOzV4rWrjNYqf1TbsDNUNMj3EMDzU03bWhzM41gq48VEZ9gGGqfZl24E2rmr5mjO02l1ISJy5oCthWXqCEWwWyQDeTG5hZAFAme64q_3FYq1xlteMFsB9wpBFoRMPA3Q: class extends self.ISpriteInstance {},
	Caption3: class extends self.ITextInstance {},
	Caption2: class extends self.ITextInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Caption4: class extends self.ITextInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	DialogueText3: class extends self.ITextInstance {},
	imrs: class extends self.ISpriteInstance {},
	Caption5: class extends self.ITextInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	DialogueText4: class extends self.ITextInstance {},
	e3e2e3fa5af344168d7e54d687bf276d: class extends self.ISpriteInstance {},
	Caption6: class extends self.ITextInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	TextOnSign: class extends self.ITextInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	DialogueXTRA: class extends self.ITextInstance {},
	children: class extends self.ISpriteInstance {},
	prisoners: class extends self.ISpriteInstance {},
	Caption7: class extends self.ITextInstance {},
	Caption8: class extends self.ITextInstance {},
	Sprite19: class extends self.ISpriteInstance {}
}